name: Retrieve Transaction by reference - failure
slug: retrieve-transaction-by-reference-failure
use_case: Transactions
behavior: negative
description: |
  Service Provider requests their own account transaction history through the Mobile Money API and the Mobile Money Provider handles the request and responds synchronously with an error indicating a format error in the request, specifically an identifierType.
precondition: |
  - Mobile Money Operator has GSMA Mobile Money API Implemented.
  - Required Parameters for Execution:
    - transactionReference should be a valid value to the system reply with a valid transaction information.
  - Define the envrionment variables to customise this test case:
    - `TRANSACTION_REFERENCE`, default value is `99999999-2223-4e3d-8333-93534e4f910c`
components:
  - name: 'Mobile Money API Provider'
    slug: mmap
  - name: 'Service Provider'
    slug: sp
test_steps:
  ## 1 ------------------------------GET /transaction: SP -> MMO1 ------------------------------##
  - path: /transactions/{transactionReference}
    pattern: '^transactions/^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$'
    method: GET
    source: sp
    target: mmap
    api_spec: MM v1.1.3
    test_response_scripts:
      - name: Transaction was successfully Rejected
        rules:
          status: 'required|in:404'
      - name: Error category is valid
        rules:
          body.errorCategory: 'required|in:identification'
      - name: Error code is valid
        rules:
          body.errorCode: 'required|in:identifierError'
    request:
      method: 'GET'
      uri:
        'transactions/{{
        env.TRANSACTION_REFERENCE|default("99999999-2223-4e3d-8333-93534e4f910c")
        }}'
      headers:
        Content-Type: 'application/json'
        X-Date: '{{ new_date_iso8601() }}'
    response:
      status: 404
      headers:
        Content-Type: 'application/json'
        X-Date: '{{ new_date_iso8601() }}'
      body:
        errorCategory: 'identification'
        errorCode: 'identifierError'
